version: '3.9'
services:
  zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper
    restart: always
    volumes:
      - ./zookeeper/zookeeper_data:/var/lib/zookeeper/data
      - ./zookeeper/zookeeper_log:/var/lib/zookeeper/log
    expose:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    networks: ["sml_service_network"]
  kafka:
    image: bitnami/kafka:3.1.0
    container_name: kafka
    restart: always
    ports:
      - 9093:9093
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://${SERVER_IP}:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    volumes:
      - ./kafka-persistence:/bitnami/kafka
    networks: ["sml_service_network"]
  postgresql_11_debezium:
    image: smlsoft/postgres:11-debezium
    container_name: sml_debezium_postgresql
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks: ["sml_service_network"]
  debezium_connect:
    image: quay.io/debezium/connect:2.1
    container_name: sml_debezium_connect
    restart: always
    ports:
     - 8083:8083
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks: ["sml_service_network"]
    depends_on:
      - zookeeper
      - kafka
      - postgresql_11_debezium
networks:
  sml_service_network:
    name: sml_service_network
    external: true