version: '3.9'
services:
  zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper
    restart: always
    volumes:
      - ./zookeeper/zookeeper_data:/var/lib/zookeeper/data
      - ./zookeeper/zookeeper_log:/var/lib/zookeeper/log
    expose:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    networks: ["sml_service_network"]
  kafka:
    image: bitnami/kafka:3.1.0
    container_name: kafka
    restart: always
    ports:
      - 9093:9093
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://${SERVER_IP}:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    volumes:
      - ./kafka-persistence:/bitnami/kafka
    networks: ["sml_service_network"]
  postgresql_11_debezium:
    image: smlsoft/postgres:11-debezium
    container_name: sml_debezium_postgresql
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks: ["sml_service_network"]
  debezium_connect:
    image: quay.io/debezium/connect:2.1
    container_name: sml_debezium_connect
    restart: always
    ports:
     - 8083:8083
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks: ["sml_service_network"]
    depends_on:
      - zookeeper
      - kafka
      - postgresql_11_debezium
  product_dealer_sync:
    image: ghcr.io/smlsoft/product-dealer-sync:stable
    container_name: product_dealer_sync
    restart: always
    expose:
      - 80
    ports:
      - 8006:80
    environment:
        - CONNECTIONSTRINGS__JOBMANAGERCONNECTION=Host=sml_debezium_postgresql;Port=5432;Username=postgres;Password=${PG_PASSWORD};Database=${PG_SML_DATABASE_NAME}
        - CONNECTIONSTRINGS__SMLCONNECTION=Host=sml_debezium_postgresql;Port=5432;Username=postgres;Password=${PG_PASSWORD};Database=${PG_SML_DATABASE_NAME}
        - PRODUCTDEALERAPI__APIKEY=${DEALER_API_KEY}
    networks: ["sml_service_network"]
    labels:
        - "traefik.http.routers.productsync.rule=(PathPrefix(`/productsyncdashboard`))"
    depends_on:
      - zookeeper
      - kafka
      - postgresql_11_debezium
      - debezium_connect
  initial-sync:
    image: ghcr.io/smlcloudplatform/smlpgconsumersyncinitial:stable
    environment:
      - DEBEZIUM_CONNECTOR_URI=http://sml_debezium_connect:8083
      - POSTGRES_HOST=sml_debezium_postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB_NAME=${PG_SML_DATABASE_NAME}
    networks: ["sml_service_network"]
    depends_on:
      - zookeeper
      - kafka
      - postgresql_11_debezium
      - debezium_connect
  smlpgconsumer:
    image: ghcr.io/smlcloudplatform/smlpgconsumersync:stable
    restart: always
    environment:
      - LOG_LEVEL=error
      - KAFKA_SERVER_URL=kafka:9092
      - POSTGRES_HOST=sml_debezium_postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=${PG_SML_DATABASE_NAME}
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_SSL_MODE=disable
      - POSTGRES_LOGGER_LEVEL=error
      - DEALER_API_URL=https://dealer-api-sml.dohome.co.th
      - DEALER_API_APP_API_KEY=${DEALER_API_KEY}
    networks: ["sml_service_network"]
    depends_on:
      - zookeeper
      - kafka
      - postgresql_11_debezium
      - debezium_connect
      - initial-sync
networks:
  sml_service_network:
    name: sml_service_network
    external: true