version: '3.9'

services:
  smldatasync:
    image: ghcr.io/smlcloudplatform/smldbsync:develop
    container_name: smldbsync
    restart: always
    environment:
      - LOG_LEVEL=debug
      - POSTGRES_HOST=sml_debezium
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=data1
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=sml
      - POSTGRES_SSL_MODE=disable
      - POSTGRES_LOGGER_LEVEL=error
      - DEALER_API_URL=http://dealer-api-sml.dohome.co.th
      - DEALER_API_APP_API_KEY=EDIT_DEALER_API_KEY
      - SYNCTABLES=ar_customer_detail,ar_dealer,coupon_list,ic_inventory_barcode,ic_inventory_price_formula,ic_promotion,ic_promotion_detail,ic_promotion_formula,ic_promotion_formula_action,ic_promotion_formula_group_qty,ic_promotion_formula_price_discount,ic_unit_use
    networks: ["sml_service_network"]
networks:
  sml_service_network:
    name: sml_service_network
    external: true
