version: '3.9'

services:
  product_dealer_sync:
    image: ghcr.io/smlsoft/product-dealer-sync:develop
    container_name: product_dealer_sync
    restart: always
    expose:
      - 80
    ports:
      - 8006:80
    environment:
        - CONNECTIONSTRINGS__JOBMANAGERCONNECTION=Host=sml_postgresql;Port=5432;Username=postgres;Password=sml;Database=EDIT_DATABASE_NAME
        - CONNECTIONSTRINGS__SMLCONNECTION=Host=sml_postgresql;Port=5432;Username=postgres;Password=sml;Database=EDIT_DATABASE_NAME
        - CONNECTIONSTRINGS__SMLDATATESTCONNECTION=Host=sml_postgresql;Port=5432;Username=postgres;Password=sml;Database=EDIT_DATABASE_NAME
        - SMLCENTERAPI__URI=https://dealer-api-sml.dohome.co.th/smlmarinecenter/api/v1/
        - DOMARINEPRODUCTAPI__URI=https://api-public.dohome.technology
        - DOMARINEPRODUCTAPI__DEALERID=EDIT_DEALER_API_KEY
        - DOMARINEPRODUCTAPI__APIKEY=marine
        - DOMARINEPRODUCTAPI__APISECRET=D0h0m3*mar1ne
    networks: ["sml_service_network"]
    labels:
        - "traefik.http.routers.productsync.rule=(PathPrefix(`/productsyncdashboard`) || PathPrefix(`/productsync`))"
networks:
  sml_service_network:
    name: sml_service_network
    external: true
