version: '3.9'

services:
  product_dealer_sync:
    image: ghcr.io/smlsoft/product-dealer-sync:stable
    container_name: product_dealer_sync
    restart: always
    expose:
      - 80
    ports:
      - 8006:80
    environment:
        - CONNECTIONSTRINGS__JOBMANAGERCONNECTION=Host=sml_debezium_postgresql;Port=5432;Username=postgres;Password=${PG_PASSWORD};Database=${PG_SML_DATABASE_NAME}
        - CONNECTIONSTRINGS__SMLCONNECTION=Host=sml_debezium_postgresql;Port=5432;Username=postgres;Password=${PG_PASSWORD};Database=${PG_SML_DATABASE_NAME}
        - PRODUCTDEALERAPI__APIKEY=${DEALER_API_KEY}
    networks: ["sml_service_network"]
    labels:
        - "traefik.http.routers.productsync.rule=(PathPrefix(`/productsyncdashboard`))"
networks:
  sml_service_network:
    name: sml_service_network
    external: true